---

- name: Install avahi-daemon package
  ansible.builtin.apt:
    pkg: avahi-daemon
    state: present

- name: Install avahi-utils package
  ansible.builtin.apt:
    pkg: avahi-utils
    state: present
  when: avahi_install_utils

- name: Avahi | Update avahi config
  ansible.builtin.template:
    src: avahi-daemon.conf.j2
    dest: "/etc/avahi/avahi-daemon.conf"
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart avahi-daemon
